### ISSUE TITLE
Trying to create backport bugs fails due to 'assignee' field

### ISSUE THREAD

**Issue by jlebon** [coreos/rhcosbot#4]
> @rhcos-bug-bot backport OCPBUGS-1505 4.10

In bot DM:

```
Traceback (most recent call last):
  File "/usr/local/bin/rhcosbot.py", line 508, in wrapper
    return f(config, *args, **kwargs)
  File "/usr/local/bin/rhcosbot.py", line 591, in wrapper
    f(self, *args)
  File "/usr/local/bin/rhcosbot.py", line 732, in _backport
    cur_issue = self._jira.api.create_issue(fields=fields)
  File "/usr/local/lib/python3.10/site-packages/jira/client.py", line 1518, in create_issue
    r = self._session.post(url, data=json.dumps(data))
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/jira/resilientsession.py", line 223, in request
    elif raise_on_error(response, **processed_kwargs):
  File "/usr/local/lib/python3.10/site-packages/jira/resilientsession.py", line 69, in raise_on_error
    raise JIRAError(
jira.exceptions.JIRAError: JiraError HTTP 400 url: https://issues.redhat.com/rest/api/2/issue
    
    response headers = {...}
    response text = {"errorMessages":[],"errors":{"assignee":"Field 'assignee' cannot be set. It is not on the appropriate screen, or unknown."}}
```

**Comment by bgilbert** [comment]
Fixed in acc945ef7c8ee8ce13734377cf42d8aea76e5f00.
